server:
  port: 8899
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?characterEncoding=utf-8&useSSL=false
    username: root
    password: root

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:META-INF/banana/services/mapper/*.xml
  type-aliases-package: org.banana.demo.model
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true