package org.banana.demo.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.banana.demo.model.DemoTab;
import org.banana.demo.model.DemoTabExample;

public interface DemoTabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_tab
     *
     * @mbg.generated Wed Dec 15 18:09:42 CST 2021
     */
    long countByExample(DemoTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_tab
     *
     * @mbg.generated Wed Dec 15 18:09:42 CST 2021
     */
    int deleteByExample(DemoTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_tab
     *
     * @mbg.generated Wed Dec 15 18:09:42 CST 2021
     */
    int insert(DemoTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_tab
     *
     * @mbg.generated Wed Dec 15 18:09:42 CST 2021
     */
    int insertSelective(DemoTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_tab
     *
     * @mbg.generated Wed Dec 15 18:09:42 CST 2021
     */
    List<DemoTab> selectByExample(DemoTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_tab
     *
     * @mbg.generated Wed Dec 15 18:09:42 CST 2021
     */
    int updateByExampleSelective(@Param("record") DemoTab record, @Param("example") DemoTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_tab
     *
     * @mbg.generated Wed Dec 15 18:09:42 CST 2021
     */
    int updateByExample(@Param("record") DemoTab record, @Param("example") DemoTabExample example);
}