package org.banana.demo.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.banana.demo.model.Test;
import org.banana.demo.model.TestExample;

public interface TestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Mon Mar 22 15:29:59 CST 2021
     */
    long countByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Mon Mar 22 15:29:59 CST 2021
     */
    int deleteByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Mon Mar 22 15:29:59 CST 2021
     */
    int insert(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Mon Mar 22 15:29:59 CST 2021
     */
    int insertSelective(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Mon Mar 22 15:29:59 CST 2021
     */
    List<Test> selectByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Mon Mar 22 15:29:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") Test record, @Param("example") TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Mon Mar 22 15:29:59 CST 2021
     */
    int updateByExample(@Param("record") Test record, @Param("example") TestExample example);
}